---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pr-merged
  namespace: cicd
spec:
  params:
  - name: repository_url
    description: url of the repository ( e.g. https://github.com/owner/application )
  - name: repository_name
    description: full name of the repository ( e.g. owner/application )
  - name: application_name
    description: name of the repository ( e.g. application )
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.application_name)-pr-merged- 
      spec:
        params:
          - name: repository_url
            value: $(tt.params.repository_url)
          - name: repository_name
            value: $(tt.params.repository_name)
          - name: application_name
            value: $(tt.params.application_name)
        serviceAccountName: tekton-cicd
        pipelineRef:
          name: pr-merged # build and push and deploy to dev ( with dev/branch tag?, with a different repo I could choose the dpeloyment strategy without affecting the commits)
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pr-merged
  namespace: cicd
spec:
  params:
    - name: application_name
      value: $(body.repository.name)
    - name: repository_name
      value: $(body.repository.full_name)
    - name: repository_url
      value: $(body.repository.html_url)

