---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-trigger
  namespace: cicd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-trigger
  namespace: cicd
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggerbindings
      - triggertemplates
    verbs:
      - get
  - apiGroups:
     - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-trigger
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: tekton-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-trigger