---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-cicd
  namespace: cicd
secrets:
  - name: quay-io-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  tekton-cicd
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - create
      - list
      - patch
      - watch
      - delete
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - create
      - patch
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - patch
      - create
      - delete
      - update
  - apiGroups:
      - "networking.istio.io"
    resources:
      - gateways
    verbs:
      - get
      - patch
      - list
      - create
      - update
      - delete
  - apiGroups:
      - "networking.istio.io"
    resources:
      - virtualservices
    verbs:
      - get
      - patch
      - list
      - create
      - delete
      - update
  - apiGroups:
      - "networking.istio.io"
    resources:
      - destinationrules
    verbs:
      - get
      - patch
      - list
      - create
      - delete
      - update
  - apiGroups:
      - "networking.istio.io"
    resources:
      - sidecar
    verbs:
      - get
      - patch
      - list
      - create
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-cicd
subjects:
  - kind: ServiceAccount
    name: tekton-cicd
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-cicd
